# Generated by Django 4.0.1 on 2022-01-16 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='', max_length=255)),
                ('site_url', models.CharField(default='', max_length=255)),
                ('contact_details', models.CharField(default='', max_length=255)),
                ('email', models.EmailField(default='', max_length=254)),
                ('mobile', models.CharField(default='', max_length=20)),
                ('logo', models.ImageField(default='', upload_to='site_logo')),
                ('favicon', models.ImageField(default='', upload_to='site_favicon')),
                ('address', models.TextField(default='')),
                ('payments', models.TextField(default='')),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
