# Generated by Django 4.0.1 on 2022-01-17 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='banner',
            field=models.ImageField(default='', upload_to='site_banner'),
        ),
    ]
