# Generated by Django 4.0.1 on 2022-01-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_configuration_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='languages',
            field=models.JSONField(default=''),
        ),
    ]
