# Generated by Django 4.0.1 on 2022-01-17 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0003_configuration_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='currencies',
            field=models.TextField(default=''),
        ),
    ]
