# Generated by Django 4.0.1 on 2022-01-17 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0004_configuration_currencies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='currencies',
            field=models.JSONField(default=''),
        ),
    ]
