# Generated by Django 4.0.1 on 2022-01-17 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0006_alter_configuration_currencies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='currencies',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='languages',
            field=models.JSONField(default=dict),
        ),
    ]
