# Generated by Django 4.0.1 on 2022-01-16 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255)),
                ('sku', models.CharField(max_length=25)),
                ('price', models.FloatField(default=None)),
                ('color', models.CharField(choices=[('R', 'Red'), ('G', 'Green'), ('W', 'While'), ('B', 'Black'), ('P', 'Pink')], max_length=1)),
                ('size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('X', 'Extra Large')], max_length=1)),
                ('images', models.ImageField(default=None, upload_to='product_images')),
                ('discount', models.FloatField(default=0)),
                ('quantity', models.IntegerField(default=0)),
                ('weight', models.FloatField(default=None)),
                ('description', models.TextField(default=None)),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
            ],
        ),
    ]
