# Generated by Django 4.0.1 on 2022-01-17 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='color',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='size',
            field=models.CharField(default='', max_length=255),
        ),
    ]
