# Generated by Django 4.0.1 on 2022-01-19 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_remove_cartitem_cart_cartitem_cart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ManyToManyField(related_name='cartitem', to='cart.Cart'),
        ),
    ]
